### ISSUE TITLE
Build Generic Activity Feed

### ISSUE THREAD

**Issue by chishs** [rcos/observatory-server#667]
A good way to demonstrate the power of RCOS developers is showcasing all our activity. This should have a large 
**Goals**

- Include Github events and blog posts
- Add filtering to see certain events or projects
- Contributions
- All developers will be responsible for coming to meetings and informing the group of problems.

**Comment by vkr96** [comment]
So currently, Observatory shows active contributions, and you can already filter to see projects. Adding events is a new feature, so that we could make it more well-known if coding sessions are happening. Could you elaborate on the last bullet point?

**Comment by aeksco** [comment]
Events (casual coding sessions, hackathons, etc.) is a planned feature. Aside from that, a global activity feed is a sufficiently valuable feature to justify the development resources it will require to implement. At this point the scope of Observatory is shifting more towards course management, rather than community engagement.
